spring.application.name=hderma-clinic-backend
server.port=8080

# ---- DB: 실제 RDS(MariaDB) 연결 ----
spring.datasource.url=jdbc:mariadb://hderma-clinic-db.cfe46ucsu7eo.ap-northeast-2.rds.amazonaws.com:3306/hderma_clinic?sslMode=trust
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

# ---- AWS: 실제 키 아직 없음 ----
spring.cloud.aws.region.static=ap-northeast-2
spring.cloud.aws.credentials.access-key=dummy
spring.cloud.aws.credentials.secret-key=dummy

spring.thymeleaf.cache=false
app.upload.dir=uploads
